/* Auto-generated by snesrecomp v2 tools/v2_sync_funcs_h.py.
 * Do NOT hand-edit. Every recompiled function takes a
 * CpuState* and mutates it in place — no return values, no
 * register-packed structs. Drop custom typedefs (HdmaPtrs,
 * PairU8, OwHvPos, CollInfo, ExtCollOut, CheckPlatformCollRet,
 * CalcTiltPlatformArgs) — all v1 ABI fiction, gone.
 *
 * Per-(m, x) variants: every named function is declared in
 * five forms so cross-bank generated calls can reference any
 * variant without a side-car header dependency. Unused
 * variants are harmless (C only flags undefined REFERENCES,
 * not undefined DECLARATIONS at link time).
 */
#pragma once

#include "cpu_state.h"

/* 69 functions across all banks (5 decls each). */

void SpcUploadInit(CpuState *cpu);  /* $00:8079 alias */
RecompReturn SpcUploadInit_M0X0(CpuState *cpu);
RecompReturn SpcUploadInit_M0X1(CpuState *cpu);
RecompReturn SpcUploadInit_M1X0(CpuState *cpu);
RecompReturn SpcUploadInit_M1X1(CpuState *cpu);
void SpcUploadSetup(CpuState *cpu);  /* $00:80E8 alias */
RecompReturn SpcUploadSetup_M0X0(CpuState *cpu);
RecompReturn SpcUploadSetup_M0X1(CpuState *cpu);
RecompReturn SpcUploadSetup_M1X0(CpuState *cpu);
RecompReturn SpcUploadSetup_M1X1(CpuState *cpu);
void SpcUploadData(CpuState *cpu);  /* $00:80F7 alias */
RecompReturn SpcUploadData_M0X0(CpuState *cpu);
RecompReturn SpcUploadData_M0X1(CpuState *cpu);
RecompReturn SpcUploadData_M1X0(CpuState *cpu);
RecompReturn SpcUploadData_M1X1(CpuState *cpu);
void SetupPpuAndDma(CpuState *cpu);  /* $00:8319 alias */
RecompReturn SetupPpuAndDma_M0X0(CpuState *cpu);
RecompReturn SetupPpuAndDma_M0X1(CpuState *cpu);
RecompReturn SetupPpuAndDma_M1X0(CpuState *cpu);
RecompReturn SetupPpuAndDma_M1X1(CpuState *cpu);
void PpuConfigA(CpuState *cpu);  /* $00:8364 alias */
RecompReturn PpuConfigA_M0X0(CpuState *cpu);
RecompReturn PpuConfigA_M0X1(CpuState *cpu);
RecompReturn PpuConfigA_M1X0(CpuState *cpu);
RecompReturn PpuConfigA_M1X1(CpuState *cpu);
void PpuConfigB(CpuState *cpu);  /* $00:8419 alias */
RecompReturn PpuConfigB_M0X0(CpuState *cpu);
RecompReturn PpuConfigB_M0X1(CpuState *cpu);
RecompReturn PpuConfigB_M1X0(CpuState *cpu);
RecompReturn PpuConfigB_M1X1(CpuState *cpu);
void NmiSubEntry1(CpuState *cpu);  /* $00:843B alias */
RecompReturn NmiSubEntry1_M0X0(CpuState *cpu);
RecompReturn NmiSubEntry1_M0X1(CpuState *cpu);
RecompReturn NmiSubEntry1_M1X0(CpuState *cpu);
RecompReturn NmiSubEntry1_M1X1(CpuState *cpu);
void NmiSubEntry2(CpuState *cpu);  /* $00:8449 alias */
RecompReturn NmiSubEntry2_M0X0(CpuState *cpu);
RecompReturn NmiSubEntry2_M0X1(CpuState *cpu);
RecompReturn NmiSubEntry2_M1X0(CpuState *cpu);
RecompReturn NmiSubEntry2_M1X1(CpuState *cpu);
void WaitForVBlank(CpuState *cpu);  /* $00:8500 alias */
RecompReturn WaitForVBlank_M0X0(CpuState *cpu);
RecompReturn WaitForVBlank_M0X1(CpuState *cpu);
RecompReturn WaitForVBlank_M1X0(CpuState *cpu);
RecompReturn WaitForVBlank_M1X1(CpuState *cpu);
void ShortWait(CpuState *cpu);  /* $00:8568 alias */
RecompReturn ShortWait_M0X0(CpuState *cpu);
RecompReturn ShortWait_M0X1(CpuState *cpu);
RecompReturn ShortWait_M1X0(CpuState *cpu);
RecompReturn ShortWait_M1X1(CpuState *cpu);
void MainInit(CpuState *cpu);  /* $00:8A00 alias */
RecompReturn MainInit_M0X0(CpuState *cpu);
RecompReturn MainInit_M0X1(CpuState *cpu);
RecompReturn MainInit_M1X0(CpuState *cpu);
RecompReturn MainInit_M1X1(CpuState *cpu);
void LoadCompressedData(CpuState *cpu);  /* $00:8CAD alias */
RecompReturn LoadCompressedData_M0X0(CpuState *cpu);
RecompReturn LoadCompressedData_M0X1(CpuState *cpu);
RecompReturn LoadCompressedData_M1X0(CpuState *cpu);
RecompReturn LoadCompressedData_M1X1(CpuState *cpu);
void DecompressAndUpload(CpuState *cpu);  /* $00:8D7B alias */
RecompReturn DecompressAndUpload_M0X0(CpuState *cpu);
RecompReturn DecompressAndUpload_M0X1(CpuState *cpu);
RecompReturn DecompressAndUpload_M1X0(CpuState *cpu);
RecompReturn DecompressAndUpload_M1X1(CpuState *cpu);
void SendSpcCommand(CpuState *cpu);  /* $00:8F7B alias */
RecompReturn SendSpcCommand_M0X0(CpuState *cpu);
RecompReturn SendSpcCommand_M0X1(CpuState *cpu);
RecompReturn SendSpcCommand_M1X0(CpuState *cpu);
RecompReturn SendSpcCommand_M1X1(CpuState *cpu);
void ReadSpcResponse(CpuState *cpu);  /* $00:9043 alias */
RecompReturn ReadSpcResponse_M0X0(CpuState *cpu);
RecompReturn ReadSpcResponse_M0X1(CpuState *cpu);
RecompReturn ReadSpcResponse_M1X0(CpuState *cpu);
RecompReturn ReadSpcResponse_M1X1(CpuState *cpu);
void ConfigurePpuRegisters(CpuState *cpu);  /* $00:95AD alias */
RecompReturn ConfigurePpuRegisters_M0X0(CpuState *cpu);
RecompReturn ConfigurePpuRegisters_M0X1(CpuState *cpu);
RecompReturn ConfigurePpuRegisters_M1X0(CpuState *cpu);
RecompReturn ConfigurePpuRegisters_M1X1(CpuState *cpu);
void LoadPalettes(CpuState *cpu);  /* $00:985A alias */
RecompReturn LoadPalettes_M0X0(CpuState *cpu);
RecompReturn LoadPalettes_M0X1(CpuState *cpu);
RecompReturn LoadPalettes_M1X0(CpuState *cpu);
RecompReturn LoadPalettes_M1X1(CpuState *cpu);
void FadePalette(CpuState *cpu);  /* $00:98A5 alias */
RecompReturn FadePalette_M0X0(CpuState *cpu);
RecompReturn FadePalette_M0X1(CpuState *cpu);
RecompReturn FadePalette_M1X0(CpuState *cpu);
RecompReturn FadePalette_M1X1(CpuState *cpu);
void SetupHdma(CpuState *cpu);  /* $00:9900 alias */
RecompReturn SetupHdma_M0X0(CpuState *cpu);
RecompReturn SetupHdma_M0X1(CpuState *cpu);
RecompReturn SetupHdma_M1X0(CpuState *cpu);
RecompReturn SetupHdma_M1X1(CpuState *cpu);
void UploadTilemaps(CpuState *cpu);  /* $00:99E6 alias */
RecompReturn UploadTilemaps_M0X0(CpuState *cpu);
RecompReturn UploadTilemaps_M0X1(CpuState *cpu);
RecompReturn UploadTilemaps_M1X0(CpuState *cpu);
RecompReturn UploadTilemaps_M1X1(CpuState *cpu);
void DecompressGraphics(CpuState *cpu);  /* $00:9AAD alias */
RecompReturn DecompressGraphics_M0X0(CpuState *cpu);
RecompReturn DecompressGraphics_M0X1(CpuState *cpu);
RecompReturn DecompressGraphics_M1X0(CpuState *cpu);
RecompReturn DecompressGraphics_M1X1(CpuState *cpu);
void LoadStripeImages(CpuState *cpu);  /* $00:9CA5 alias */
RecompReturn LoadStripeImages_M0X0(CpuState *cpu);
RecompReturn LoadStripeImages_M0X1(CpuState *cpu);
RecompReturn LoadStripeImages_M1X0(CpuState *cpu);
RecompReturn LoadStripeImages_M1X1(CpuState *cpu);
void UpdateOam(CpuState *cpu);  /* $00:9D00 alias */
RecompReturn UpdateOam_M0X0(CpuState *cpu);
RecompReturn UpdateOam_M0X1(CpuState *cpu);
RecompReturn UpdateOam_M1X0(CpuState *cpu);
RecompReturn UpdateOam_M1X1(CpuState *cpu);
void PollControllers(CpuState *cpu);  /* $00:9D7B alias */
RecompReturn PollControllers_M0X0(CpuState *cpu);
RecompReturn PollControllers_M0X1(CpuState *cpu);
RecompReturn PollControllers_M1X0(CpuState *cpu);
RecompReturn PollControllers_M1X1(CpuState *cpu);
void UpdateStatusBar(CpuState *cpu);  /* $00:9EA0 alias */
RecompReturn UpdateStatusBar_M0X0(CpuState *cpu);
RecompReturn UpdateStatusBar_M0X1(CpuState *cpu);
RecompReturn UpdateStatusBar_M1X0(CpuState *cpu);
RecompReturn UpdateStatusBar_M1X1(CpuState *cpu);
void ModeHelper1(CpuState *cpu);  /* $00:9FAD alias */
RecompReturn ModeHelper1_M0X0(CpuState *cpu);
RecompReturn ModeHelper1_M0X1(CpuState *cpu);
RecompReturn ModeHelper1_M1X0(CpuState *cpu);
RecompReturn ModeHelper1_M1X1(CpuState *cpu);
void LoadLevelData(CpuState *cpu);  /* $00:A1A5 alias */
RecompReturn LoadLevelData_M0X0(CpuState *cpu);
RecompReturn LoadLevelData_M0X1(CpuState *cpu);
RecompReturn LoadLevelData_M1X0(CpuState *cpu);
RecompReturn LoadLevelData_M1X1(CpuState *cpu);
void ProcessLevelData(CpuState *cpu);  /* $00:A28B alias */
RecompReturn ProcessLevelData_M0X0(CpuState *cpu);
RecompReturn ProcessLevelData_M0X1(CpuState *cpu);
RecompReturn ProcessLevelData_M1X0(CpuState *cpu);
RecompReturn ProcessLevelData_M1X1(CpuState *cpu);
void ProcessObjects(CpuState *cpu);  /* $00:A500 alias */
RecompReturn ProcessObjects_M0X0(CpuState *cpu);
RecompReturn ProcessObjects_M0X1(CpuState *cpu);
RecompReturn ProcessObjects_M1X0(CpuState *cpu);
RecompReturn ProcessObjects_M1X1(CpuState *cpu);
void UpdateSprites(CpuState *cpu);  /* $00:A58B alias */
RecompReturn UpdateSprites_M0X0(CpuState *cpu);
RecompReturn UpdateSprites_M0X1(CpuState *cpu);
RecompReturn UpdateSprites_M1X0(CpuState *cpu);
RecompReturn UpdateSprites_M1X1(CpuState *cpu);
void CheckCollisions(CpuState *cpu);  /* $00:A98B alias */
RecompReturn CheckCollisions_M0X0(CpuState *cpu);
RecompReturn CheckCollisions_M0X1(CpuState *cpu);
RecompReturn CheckCollisions_M1X0(CpuState *cpu);
RecompReturn CheckCollisions_M1X1(CpuState *cpu);
void SendSoundCommand(CpuState *cpu);  /* $00:AA00 alias */
RecompReturn SendSoundCommand_M0X0(CpuState *cpu);
RecompReturn SendSoundCommand_M0X1(CpuState *cpu);
RecompReturn SendSoundCommand_M1X0(CpuState *cpu);
RecompReturn SendSoundCommand_M1X1(CpuState *cpu);
void Utility1(CpuState *cpu);  /* $00:AB48 alias */
RecompReturn Utility1_M0X0(CpuState *cpu);
RecompReturn Utility1_M0X1(CpuState *cpu);
RecompReturn Utility1_M1X0(CpuState *cpu);
RecompReturn Utility1_M1X1(CpuState *cpu);
void Utility2(CpuState *cpu);  /* $00:B022 alias */
RecompReturn Utility2_M0X0(CpuState *cpu);
RecompReturn Utility2_M0X1(CpuState *cpu);
RecompReturn Utility2_M1X0(CpuState *cpu);
RecompReturn Utility2_M1X1(CpuState *cpu);
void LoadMapData(CpuState *cpu);  /* $00:B164 alias */
RecompReturn LoadMapData_M0X0(CpuState *cpu);
RecompReturn LoadMapData_M0X1(CpuState *cpu);
RecompReturn LoadMapData_M1X0(CpuState *cpu);
RecompReturn LoadMapData_M1X1(CpuState *cpu);
void UpdateMap(CpuState *cpu);  /* $00:B2A0 alias */
RecompReturn UpdateMap_M0X0(CpuState *cpu);
RecompReturn UpdateMap_M0X1(CpuState *cpu);
RecompReturn UpdateMap_M1X0(CpuState *cpu);
RecompReturn UpdateMap_M1X1(CpuState *cpu);
void DecompressFetchByte(CpuState *cpu);  /* $00:B983 alias */
RecompReturn DecompressFetchByte_M0X0(CpuState *cpu);
RecompReturn DecompressFetchByte_M0X1(CpuState *cpu);
RecompReturn DecompressFetchByte_M1X0(CpuState *cpu);
RecompReturn DecompressFetchByte_M1X1(CpuState *cpu);
void LoadString(CpuState *cpu);  /* $00:B99B alias */
RecompReturn LoadString_M0X0(CpuState *cpu);
RecompReturn LoadString_M0X1(CpuState *cpu);
RecompReturn LoadString_M1X0(CpuState *cpu);
RecompReturn LoadString_M1X1(CpuState *cpu);
void SetupDmaTransfer(CpuState *cpu);  /* $00:BC5A alias */
RecompReturn SetupDmaTransfer_M0X0(CpuState *cpu);
RecompReturn SetupDmaTransfer_M0X1(CpuState *cpu);
RecompReturn SetupDmaTransfer_M1X0(CpuState *cpu);
RecompReturn SetupDmaTransfer_M1X1(CpuState *cpu);
void DecompressEngine(CpuState *cpu);  /* $00:BDE8 alias */
RecompReturn DecompressEngine_M0X0(CpuState *cpu);
RecompReturn DecompressEngine_M0X1(CpuState *cpu);
RecompReturn DecompressEngine_M1X0(CpuState *cpu);
RecompReturn DecompressEngine_M1X1(CpuState *cpu);
void FinalizeLoad(CpuState *cpu);  /* $00:BEA5 alias */
RecompReturn FinalizeLoad_M0X0(CpuState *cpu);
RecompReturn FinalizeLoad_M0X1(CpuState *cpu);
RecompReturn FinalizeLoad_M1X0(CpuState *cpu);
RecompReturn FinalizeLoad_M1X1(CpuState *cpu);
void NmiTrampoline(CpuState *cpu);  /* $00:FEB9 alias */
RecompReturn NmiTrampoline_M0X0(CpuState *cpu);
RecompReturn NmiTrampoline_M0X1(CpuState *cpu);
RecompReturn NmiTrampoline_M1X0(CpuState *cpu);
RecompReturn NmiTrampoline_M1X1(CpuState *cpu);
void IrqTrampoline(CpuState *cpu);  /* $00:FEBD alias */
RecompReturn IrqTrampoline_M0X0(CpuState *cpu);
RecompReturn IrqTrampoline_M0X1(CpuState *cpu);
RecompReturn IrqTrampoline_M1X0(CpuState *cpu);
RecompReturn IrqTrampoline_M1X1(CpuState *cpu);
void ResetHandler(CpuState *cpu);  /* $00:FEC1 alias */
RecompReturn ResetHandler_M0X0(CpuState *cpu);
RecompReturn ResetHandler_M0X1(CpuState *cpu);
RecompReturn ResetHandler_M1X0(CpuState *cpu);
RecompReturn ResetHandler_M1X1(CpuState *cpu);
void BootMmcEntry(CpuState *cpu);  /* $00:FF96 alias */
RecompReturn BootMmcEntry_M0X0(CpuState *cpu);
RecompReturn BootMmcEntry_M0X1(CpuState *cpu);
RecompReturn BootMmcEntry_M1X0(CpuState *cpu);
RecompReturn BootMmcEntry_M1X1(CpuState *cpu);
void NmiHandler(CpuState *cpu);  /* $C0:0000 alias */
RecompReturn NmiHandler_M0X0(CpuState *cpu);
RecompReturn NmiHandler_M0X1(CpuState *cpu);
RecompReturn NmiHandler_M1X0(CpuState *cpu);
RecompReturn NmiHandler_M1X1(CpuState *cpu);
void IrqHandler(CpuState *cpu);  /* $C0:0221 alias */
RecompReturn IrqHandler_M0X0(CpuState *cpu);
RecompReturn IrqHandler_M0X1(CpuState *cpu);
RecompReturn IrqHandler_M1X0(CpuState *cpu);
RecompReturn IrqHandler_M1X1(CpuState *cpu);
void Sdd1Init(CpuState *cpu);  /* $C0:0400 alias */
RecompReturn Sdd1Init_M0X0(CpuState *cpu);
RecompReturn Sdd1Init_M0X1(CpuState *cpu);
RecompReturn Sdd1Init_M1X0(CpuState *cpu);
RecompReturn Sdd1Init_M1X1(CpuState *cpu);
void SpcUpload(CpuState *cpu);  /* $C0:0600 alias */
RecompReturn SpcUpload_M0X0(CpuState *cpu);
RecompReturn SpcUpload_M0X1(CpuState *cpu);
RecompReturn SpcUpload_M1X0(CpuState *cpu);
RecompReturn SpcUpload_M1X1(CpuState *cpu);
void GameInit(CpuState *cpu);  /* $C0:0800 alias */
RecompReturn GameInit_M0X0(CpuState *cpu);
RecompReturn GameInit_M0X1(CpuState *cpu);
RecompReturn GameInit_M1X0(CpuState *cpu);
RecompReturn GameInit_M1X1(CpuState *cpu);
void MainLoop(CpuState *cpu);  /* $C0:0A00 alias */
RecompReturn MainLoop_M0X0(CpuState *cpu);
RecompReturn MainLoop_M0X1(CpuState *cpu);
RecompReturn MainLoop_M1X0(CpuState *cpu);
RecompReturn MainLoop_M1X1(CpuState *cpu);
void TaskDispatch(CpuState *cpu);  /* $C0:0C00 alias */
RecompReturn TaskDispatch_M0X0(CpuState *cpu);
RecompReturn TaskDispatch_M0X1(CpuState *cpu);
RecompReturn TaskDispatch_M1X0(CpuState *cpu);
RecompReturn TaskDispatch_M1X1(CpuState *cpu);
void DmaSetupForSdd1(CpuState *cpu);  /* $C0:0E00 alias */
RecompReturn DmaSetupForSdd1_M0X0(CpuState *cpu);
RecompReturn DmaSetupForSdd1_M0X1(CpuState *cpu);
RecompReturn DmaSetupForSdd1_M1X0(CpuState *cpu);
RecompReturn DmaSetupForSdd1_M1X1(CpuState *cpu);
void CheckSdd1Status(CpuState *cpu);  /* $C0:1000 alias */
RecompReturn CheckSdd1Status_M0X0(CpuState *cpu);
RecompReturn CheckSdd1Status_M0X1(CpuState *cpu);
RecompReturn CheckSdd1Status_M1X0(CpuState *cpu);
RecompReturn CheckSdd1Status_M1X1(CpuState *cpu);
void VBlankHandler(CpuState *cpu);  /* $C0:1200 alias */
RecompReturn VBlankHandler_M0X0(CpuState *cpu);
RecompReturn VBlankHandler_M0X1(CpuState *cpu);
RecompReturn VBlankHandler_M1X0(CpuState *cpu);
RecompReturn VBlankHandler_M1X1(CpuState *cpu);
void UploadTilemap(CpuState *cpu);  /* $C0:1400 alias */
RecompReturn UploadTilemap_M0X0(CpuState *cpu);
RecompReturn UploadTilemap_M0X1(CpuState *cpu);
RecompReturn UploadTilemap_M1X0(CpuState *cpu);
RecompReturn UploadTilemap_M1X1(CpuState *cpu);
void UpdatePaletteVBlank(CpuState *cpu);  /* $C0:1600 alias */
RecompReturn UpdatePaletteVBlank_M0X0(CpuState *cpu);
RecompReturn UpdatePaletteVBlank_M0X1(CpuState *cpu);
RecompReturn UpdatePaletteVBlank_M1X0(CpuState *cpu);
RecompReturn UpdatePaletteVBlank_M1X1(CpuState *cpu);
void BattleMain(CpuState *cpu);  /* $C0:1800 alias */
RecompReturn BattleMain_M0X0(CpuState *cpu);
RecompReturn BattleMain_M0X1(CpuState *cpu);
RecompReturn BattleMain_M1X0(CpuState *cpu);
RecompReturn BattleMain_M1X1(CpuState *cpu);
void BattleUpdate(CpuState *cpu);  /* $C0:1A00 alias */
RecompReturn BattleUpdate_M0X0(CpuState *cpu);
RecompReturn BattleUpdate_M0X1(CpuState *cpu);
RecompReturn BattleUpdate_M1X0(CpuState *cpu);
RecompReturn BattleUpdate_M1X1(CpuState *cpu);
void FieldRender(CpuState *cpu);  /* $C0:1C00 alias */
RecompReturn FieldRender_M0X0(CpuState *cpu);
RecompReturn FieldRender_M0X1(CpuState *cpu);
RecompReturn FieldRender_M1X0(CpuState *cpu);
RecompReturn FieldRender_M1X1(CpuState *cpu);
void FieldUpdate(CpuState *cpu);  /* $C0:1E00 alias */
RecompReturn FieldUpdate_M0X0(CpuState *cpu);
RecompReturn FieldUpdate_M0X1(CpuState *cpu);
RecompReturn FieldUpdate_M1X0(CpuState *cpu);
RecompReturn FieldUpdate_M1X1(CpuState *cpu);
void MenuMain(CpuState *cpu);  /* $C0:2000 alias */
RecompReturn MenuMain_M0X0(CpuState *cpu);
RecompReturn MenuMain_M0X1(CpuState *cpu);
RecompReturn MenuMain_M1X0(CpuState *cpu);
RecompReturn MenuMain_M1X1(CpuState *cpu);
void MenuUpdate(CpuState *cpu);  /* $C0:2200 alias */
RecompReturn MenuUpdate_M0X0(CpuState *cpu);
RecompReturn MenuUpdate_M0X1(CpuState *cpu);
RecompReturn MenuUpdate_M1X0(CpuState *cpu);
RecompReturn MenuUpdate_M1X1(CpuState *cpu);
void AcknowledgeIrq(CpuState *cpu);  /* $C0:2400 alias */
RecompReturn AcknowledgeIrq_M0X0(CpuState *cpu);
RecompReturn AcknowledgeIrq_M0X1(CpuState *cpu);
RecompReturn AcknowledgeIrq_M1X0(CpuState *cpu);
RecompReturn AcknowledgeIrq_M1X1(CpuState *cpu);
void NmiComplete(CpuState *cpu);  /* $C0:2600 alias */
RecompReturn NmiComplete_M0X0(CpuState *cpu);
RecompReturn NmiComplete_M0X1(CpuState *cpu);
RecompReturn NmiComplete_M1X0(CpuState *cpu);
RecompReturn NmiComplete_M1X1(CpuState *cpu);
void BlitMenuTiles(CpuState *cpu);  /* $C2:FC43 alias */
RecompReturn BlitMenuTiles_M0X0(CpuState *cpu);
RecompReturn BlitMenuTiles_M0X1(CpuState *cpu);
RecompReturn BlitMenuTiles_M1X0(CpuState *cpu);
RecompReturn BlitMenuTiles_M1X1(CpuState *cpu);
void StarField(CpuState *cpu);  /* $C3:8F50 alias */
RecompReturn StarField_M0X0(CpuState *cpu);
RecompReturn StarField_M0X1(CpuState *cpu);
RecompReturn StarField_M1X0(CpuState *cpu);
RecompReturn StarField_M1X1(CpuState *cpu);
void LayoutTableIndexA(CpuState *cpu);  /* $C9:E4DC alias */
RecompReturn LayoutTableIndexA_M0X0(CpuState *cpu);
RecompReturn LayoutTableIndexA_M0X1(CpuState *cpu);
RecompReturn LayoutTableIndexA_M1X0(CpuState *cpu);
RecompReturn LayoutTableIndexA_M1X1(CpuState *cpu);
void LayoutTableIndexB(CpuState *cpu);  /* $C9:E57B alias */
RecompReturn LayoutTableIndexB_M0X0(CpuState *cpu);
RecompReturn LayoutTableIndexB_M0X1(CpuState *cpu);
RecompReturn LayoutTableIndexB_M1X0(CpuState *cpu);
RecompReturn LayoutTableIndexB_M1X1(CpuState *cpu);

/* Hand-written non-recompiled bodies still declared here.
 * These are not produced by the v2 emit pipeline but are
 * referenced by recompiled code via funcs.h.
 */
void ResetSpritesFunc(int wh);
void RunOneFrameOfGame_Internal(void);

/* Watchdog hook called at every block label. Implemented in
 * snesrecomp/runner/src/common_cpu_infra.c.
 */
void WatchdogCheck(void);
